Repository robbievanleeuwen/section-properties, pull requests merged in 2021-12, with the labels that each got.

#130 Vector plot fix
  sectionproperties/analysis/cross_section.py
Labels: bug

#125 Minor running analysis changes
  sectionproperties/analysis/cross_section.py
Labels: documentation

#127 'Viewing the Results' update
  docs/source/conf.py
  docs/source/images/stress/stress_1.png
  docs/source/images/stress/stress_2.png
  docs/source/images/stress/stress_3.png
  docs/source/rst/post.rst
  docs/source/rst/theory.rst
  sectionproperties/analysis/cross_section.py
Labels: documentation

#131 Fix vertical line detection in create_line_segment
  sectionproperties/pre/bisect_section.py
Labels: bug

#136 Implement calculation of cross-section mass
  docs/source/rst/advanced_geom.rst
  docs/source/rst/examples.rst
  docs/source/rst/post.rst
  docs/source/rst/structure.rst
  sectionproperties/analysis/cross_section.py
  sectionproperties/analysis/fea.py
  sectionproperties/post/post.py
  sectionproperties/pre/pre.py
  sectionproperties/tests/test_rectangle.py
  sectionproperties/tests/test_sections.py
Labels: enhancement

#135 Fix sectionproperties logo
  README.md
  docs/source/images/logo.png
  logo.png
Labels: documentation

#133 Compound from points (#113)
  docs/source/images/examples/nested_compound.png
  docs/source/images/examples/nested_compound_via_shapely.png
  docs/source/images/examples/nested_compound_via_triangle.png
  docs/source/images/examples/shapely_z_ordering.png
  docs/source/images/examples/triangle_no_z_order.png
  docs/source/rst/advanced_geom.rst
  sectionproperties/pre/sections.py
  sectionproperties/tests/test_sections.py
  sectionproperties/tests/test_validation.py
Labels: bug, enhancement

#138 Modify figure size behaviour
  sectionproperties/analysis/cross_section.py
  sectionproperties/post/post.py
  sectionproperties/pre/sections.py
Labels: bug

#140 Perimeter & offset tests; CompundGeometry offset fix
  sectionproperties/pre/sections.py
  sectionproperties/tests/test_offset.py
  sectionproperties/tests/test_perimeter.py
  sectionproperties/tests/test_sections.py
Labels: bug

#153 Switch to triangle
  README.md
  docs/source/requirements_docs.txt
  docs/source/rst/advanced_geom.rst
  docs/source/rst/installation.rst
  docs/source/rst/theory.rst
  sectionproperties/analysis/cross_section.py
  sectionproperties/pre/pre.py
  setup.py
Labels: enhancement

#132 New section library
  docs/source/conf.py
  docs/source/images/sections/concrete_circular_section_geometry.png
  docs/source/images/sections/concrete_circular_section_mesh.png
  docs/source/images/sections/concrete_rectangular_section_geometry.png
  docs/source/images/sections/concrete_rectangular_section_mesh.png
  docs/source/images/sections/concrete_tee_section_geometry.png
  docs/source/images/sections/concrete_tee_section_mesh.png
  docs/source/index.rst
  docs/source/rst/advanced_geom.rst
  docs/source/rst/api.rst
  docs/source/rst/geom_mesh.rst
  docs/source/rst/post.rst
  docs/source/rst/section_library.rst
  docs/source/rst/structure.rst
  examples/00-basic/01_simple.py
  examples/00-basic/02_nastran_section.py
  examples/00-basic/03_custom.py
  examples/00-basic/04_merged.py
  examples/00-basic/05_mirr_rot.py
  examples/00-basic/06_stress.py
  examples/00-basic/07_composite.py
  examples/00-basic/08_frame.py
  examples/01-advanced/01-torsion_constant.py
  examples/01-advanced/02-mesh_refinement.py
  sectionproperties/analysis/section.py
  sectionproperties/pre/bisect_section.py
  sectionproperties/pre/dxf.py
  sectionproperties/pre/geometry.py
  sectionproperties/pre/library/bridge_sections.py
  sectionproperties/pre/library/concrete_sections.py
  sectionproperties/pre/library/nastran_sections.py
  sectionproperties/pre/library/standard_sections.py
  sectionproperties/pre/library/steel_sections.py
  sectionproperties/pre/library/utils.py
  sectionproperties/tests/test_offset.py
  sectionproperties/tests/test_perimeter.py
  sectionproperties/tests/test_rectangle.py
  sectionproperties/tests/test_sections.py
  sectionproperties/tests/test_validation.py
Labels: enhancement
