Repository robbievanleeuwen/section-properties, pull requests merged in 2023-09, with the labels that each got.

#287 Composite results changes
  .github/workflows/constraints.txt
  docs/examples/geometry/section_library.ipynb
  poetry.lock
  pyproject.toml
  src/sectionproperties/analysis/section.py
  src/sectionproperties/post/post.py
  tests/test_get_results.py
  tests/test_plastic.py
Labels: engineering, documentation

#291 Improve plot options
  docs/examples/advanced/advanced_plot.ipynb
  docs/examples/advanced/rectangle_torsion.ipynb
  docs/examples/analysis/stress_analysis.ipynb
  docs/examples/geometry/advanced_geometry.ipynb
  docs/examples/materials/composite_analysis.ipynb
  docs/examples/results/get_stress.ipynb
  docs/examples/results/plot_centroids.ipynb
  docs/examples/results/plot_stress.ipynb
  src/sectionproperties/analysis/section.py
  src/sectionproperties/post/stress_post.py
Labels: enhancement

#290 Add option to specify minimum mesh angle
  docs/examples/geometry/create_mesh.ipynb
  src/sectionproperties/pre/geometry.py
  src/sectionproperties/pre/pre.py
Labels: enhancement

#292 Expose spline dxf import options
  src/sectionproperties/pre/geometry.py
Labels: enhancement

#294 Remove Geometry.from_points() docstring that states facet list can be optional
  src/sectionproperties/pre/geometry.py
Labels: documentation

#296 Fix progress bar not working for geometric and plastic analysis
  src/sectionproperties/analysis/plastic_section.py
  src/sectionproperties/analysis/section.py
Labels: bug

#293 Add cache, improve performance
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/section.py
Labels: enhancement, engineering
