Repository robbievanleeuwen/section-properties, pull requests merged in 2023-10, with the labels that each got.

#295 Plugin fibre section
  docs/examples.rst
  docs/examples/analysis/export_fibre_section.ipynb
  src/sectionproperties/post/fibre.py
Labels: enhancement

#289 Add python 3.11 support, drop python 3.8
  .github/workflows/tests.yml
  docs/installation.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/test_geometry.py
Labels: enhancement

#297 Proposed fix for non-recognized holes
  src/sectionproperties/pre/geometry.py
Labels: bug

#300 Allow unlipped cee and zed steel_sections
  src/sectionproperties/pre/library/steel_sections.py
Labels: enhancement

#322 Fix concrete_rectangular_section() bug when n_side=1
  src/sectionproperties/pre/library/concrete_sections.py
Labels: bug

#323 Bump coverage (7.3.1 to 7.3.2), pyupgrade (3.13.0 to 3.14.0) and prettier (2.7.1 to 3.0.3)
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies, python

#325 Fix concrete_tee_section() top bar distribution
  docs/user_guide/geometry.rst
  src/sectionproperties/pre/library/concrete_sections.py
Labels: bug

#326 Fix links in documentation
  README.md
  src/sectionproperties/analysis/section.py
Labels: documentation

#327 Update noxfile.py with correct docs dependencies, fix double CI builds
  .github/workflows/tests.yml
  .gitignore
  noxfile.py
Labels: ci

#328 Bump jupyter/nbconvert from 7.8.0 to 7.9.2
  poetry.lock
  pyproject.toml
Labels: dependencies

#330 Fix docstring for StressPost.get_stress()
  src/sectionproperties/post/stress_post.py
Labels: documentation

#329 Restructure tests directory, add further validation tests (including many examples from Pilkey), improve tests coverage, add flake8-pytest-style
  .darglint
  .flake8
  docs/user_guide/validation.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  src/sectionproperties/analysis/section.py
  src/sectionproperties/post/stress_post.py
  src/sectionproperties/pre/geometry.py
  src/sectionproperties/pre/library/nastran_sections.py
  tests/analysis/__init__.py
  tests/analysis/test_plastic.py
  tests/analysis/test_stress.py
  tests/cli/__init__.py
  tests/cli/test_main.py
  tests/geometry/3in x 2in.3dm
  tests/geometry/__init__.py
  tests/geometry/complex_shape.3dm
  tests/geometry/complex_shape.txt
  tests/geometry/compound_shape.3dm
  tests/geometry/compound_shape.txt
  tests/geometry/rhino_data.json
  tests/geometry/section_holes.dxf
  tests/geometry/test_geometry.py
  tests/geometry/test_offset.py
  tests/geometry/test_perimeter.py
  tests/post/__init__.py
  tests/post/test_get_results.py
  tests/post/test_post.py
  tests/post/test_stress_post.py
  tests/section_library/__init__.py
  tests/section_library/test_concrete_sections.py
  tests/test_rectangle.py
  tests/test_validation.py
  tests/validation/__init__.py
  tests/validation/test_angle_validation.py
  tests/validation/test_custom_validation.py
  tests/validation/test_peery.py
  tests/validation/test_pilkey.py
  tests/validation/test_rectangle_validation.py
Labels: ci, testing

#333 Add nbQA to pre-commit (runs black, isort and pyupgrade on jupyter notebooks)
  .pre-commit-config.yaml
  docs/examples/advanced/advanced_plot.ipynb
  docs/examples/advanced/peery.ipynb
  docs/examples/advanced/rectangle_torsion.ipynb
  docs/examples/advanced/trapezoidal_torsion.ipynb
  docs/examples/analysis/export_fibre_section.ipynb
  docs/examples/analysis/frame_analysis.ipynb
  docs/examples/analysis/geometric_analysis.ipynb
  docs/examples/analysis/plastic_analysis.ipynb
  docs/examples/analysis/stress_analysis.ipynb
  docs/examples/analysis/warping_analysis.ipynb
  docs/examples/geometry/advanced_geometry.ipynb
  docs/examples/geometry/create_mesh.ipynb
  docs/examples/geometry/geometry_cad.ipynb
  docs/examples/geometry/geometry_coordinates.ipynb
  docs/examples/geometry/geometry_manipulation.ipynb
  docs/examples/geometry/section_library.ipynb
  docs/examples/materials/assign_materials.ipynb
  docs/examples/materials/composite_analysis.ipynb
  docs/examples/results/display_results.ipynb
  docs/examples/results/get_results.ipynb
  docs/examples/results/get_stress.ipynb
  docs/examples/results/plot_centroids.ipynb
  docs/examples/results/plot_stress.ipynb
  noxfile.py
  poetry.lock
  pyproject.toml
Labels: ci

#334 Bump pre-commit-hooks from 4.4.0 to 4.5.0, pyupgrade from 3.14.0 to 3.15.0
  poetry.lock
  pyproject.toml
Labels: dependencies

#335 Add validation examples from Pilkey (Symmetric Channel Section, Circular Arc, Composite Rectangular Strip)
  docs/examples.rst
  docs/examples/results/export_fibre_section.ipynb
  docs/examples/validation/images/arc-geom.png
  docs/examples/validation/images/arc-mesh.png
  docs/examples/validation/images/channel-geom.png
  docs/examples/validation/images/channel-mesh.png
  docs/examples/validation/images/comp-geom.png
  docs/examples/validation/images/comp-mesh.png
  docs/examples/validation/peery.ipynb
  docs/examples/validation/pilkey_arc.ipynb
  docs/examples/validation/pilkey_channel.ipynb
  docs/examples/validation/pilkey_composite.ipynb
  docs/user_guide/validation.rst
  tests/validation/test_pilkey.py
Labels: documentation

#336 Add benchmark tests
  .flake8
  .gitignore
  CONTRIBUTING.md
  docs/contributing.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/benchmarks/__init__.py
  tests/benchmarks/conftest.py
  tests/benchmarks/test_benchmark_analysis.py
  tests/benchmarks/test_benchmark_geom.py
  tests/benchmarks/test_benchmark_mesh.py
Labels: testing

#337 Bump rhino3dm from 8.0.0b2 to 8.0.0b3, remove python 3.10 & 3.11 restriction for `rhino` extra
  CONTRIBUTING.md
  docs/contributing.rst
  docs/installation.rst
  docs/user_guide/geometry.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  tests/benchmarks/test_benchmark_analysis.py
  tests/benchmarks/test_benchmark_geom.py
  tests/benchmarks/test_benchmark_mesh.py
  tests/geometry/test_geometry.py
Labels: dependencies

#338 Build docs with python 3.10, pre-commit with python 3.11
  .github/workflows/release.yml
  .github/workflows/tests.yml
  .readthedocs.yaml
  noxfile.py
Labels: build

#339 Exclude benchmarks from test coverage
  pyproject.toml
  tests/post/test_post.py
Labels: testing

#324 Add numba, pardiso
  docs/installation.rst
  poetry.lock
  pyproject.toml
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/section.py
  src/sectionproperties/analysis/solver.py
Labels: performance

#341 `Section.calculate_stress()` fixes - suppress numba performance warning, fix time info stuck at 0%
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/section.py
Labels: bug

#343 Add `plot_warping_function()`, enforce Lagrangian Multiplier constraint
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/section.py
Labels: enhancement

#345 Plot warping function only over section extents
  src/sectionproperties/analysis/section.py
Labels: bug

#344 Implement `mypy`
  .github/workflows/tests.yml
  .gitignore
  noxfile.py
  poetry.lock
  pyproject.toml
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/plastic_section.py
  src/sectionproperties/analysis/section.py
  src/sectionproperties/analysis/solver.py
  src/sectionproperties/post/fibre.py
  src/sectionproperties/post/post.py
  src/sectionproperties/post/stress_post.py
  src/sectionproperties/pre/bisect_section.py
  src/sectionproperties/pre/geometry.py
  src/sectionproperties/pre/library/concrete_sections.py
  src/sectionproperties/pre/library/nastran_sections.py
  src/sectionproperties/pre/library/steel_sections.py
  src/sectionproperties/pre/pre.py
  src/sectionproperties/pre/rhino.py
Labels: style

#349 Make `numba` an optional dependency
  .readthedocs.yaml
  docs/installation.rst
  noxfile.py
  poetry.lock
  pyproject.toml
  src/sectionproperties/analysis/fea.py
Labels: build

#350 Relax core dependencies for better compatibility, bump dev dependencies
  .pre-commit-config.yaml
  poetry.lock
  pyproject.toml
Labels: dependencies

#352 Fix optional njit decorator
  src/sectionproperties/analysis/fea.py
  src/sectionproperties/analysis/solver.py
Labels: bug
