Repository robbievanleeuwen/section-properties, pull requests merged in 2024-06, with the labels that each got.

#439 Update dependencies to swap in cytriangle
  .github/workflows/tests.yml
  poetry.lock
  pyproject.toml
  src/sectionproperties/pre/pre.py
Labels: enhancement

#443 Update references to CyTriangle
  docs/examples/geometry/advanced_geometry.ipynb
  docs/installation.rst
  docs/user_guide/theory.rst
  src/sectionproperties/analysis/section.py
  src/sectionproperties/pre/pre.py
Labels: documentation

#444 Fix `scipy` deprecation for `sparse.linalg.cgs()`
  src/sectionproperties/analysis/solver.py
Labels: bug
