Repository robbievanleeuwen/section-properties, pull requests merged in 2025-03, with the labels that each got.

#512 Bump uv from 0.5.2 to 0.6.4
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: dependencies

#514 Bump astral-sh/ruff-pre-commit from 0.8.0 to 0.9.9
  .pre-commit-config.yaml
Labels: dependencies

#515 Bump ipympl from 0.9.4 to 0.9.7
  pyproject.toml
  uv.lock
Labels: dependencies

#522 Bump pytest from 8.3.3 to 8.3.5
  pyproject.toml
  uv.lock
Labels: dependencies

#521 Bump pre-commit from 4.0.1 to 4.1.0
  pyproject.toml
  uv.lock
Labels: dependencies

#520 Bump nbconvert from 7.16.4 to 7.16.6
  pyproject.toml
  uv.lock
Labels: dependencies

#518 Bump ipython from 8.29.0 to 9.0.1
  pyproject.toml
Labels: dependencies

#523 Bump pytest-check from 2.4.1 to 2.5.0
  pyproject.toml
  uv.lock
Labels: dependencies

#527 Bump notebook from 7.2.2 to 7.3.2
  pyproject.toml
Labels: dependencies

#528 Drop python 3.10 support
  .github/workflows/ci.yml
  docs/installation.rst
  pyproject.toml
  ruff.toml
  uv.lock
Labels: breaking

#529 Bump nbsphinx from 0.9.5 to 0.9.7
  pyproject.toml
  uv.lock
Labels: dependencies

#530 Bump coverage from 7.6.8 to 7.6.12
  pyproject.toml
  uv.lock
Labels: dependencies

#531 Bump pyright from 1.1.389 to 1.1.396
  pyproject.toml
  src/sectionproperties/pre/geometry.py
  uv.lock
Labels: dependencies

#532 Bump cytriangle from 1.0.3 to 2.0.0
  pyproject.toml
  uv.lock
Labels: dependencies

#533 Bump shapely from 2.0.6 to 2.0.7
  pyproject.toml
  uv.lock
Labels: dependencies

#534 Bump rhino3dm from 8.9.0 to 8.17.0b0
  pyproject.toml
  uv.lock
Labels: dependencies

#535 Support python 3.13
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .python-version
  .readthedocs.yaml
  CONTRIBUTING.md
  docs/contributing.rst
  docs/installation.rst
  pyproject.toml
  uv.lock
Labels: enhancement

#536 Swap `find_holes` out for `filter_polygons` in `load_dxf` (`geometry.py`)
  src/sectionproperties/pre/geometry.py
  typings/cad_to_shapely/__init__.pyi
  typings/cad_to_shapely/utils.pyi
Labels: dependencies

#537 Bump version to v3.8.0
  .github/release-drafter.yml
  pyproject.toml
  uv.lock
Labels: dependencies

#466 Add rectangular CLT section to (new) timber sections library
  docs/examples/geometry/section_library.ipynb
  docs/user_guide/geometry.rst
  src/sectionproperties/pre/library/__init__.py
  src/sectionproperties/pre/library/timber_sections.py
  tests/section_library/test_timber_sections.py
Labels: enhancement
